### ISSUE TITLE
Problems with Block-script

### ISSUE THREAD

**Issue by joppiesaus** [waldenn/spirare#12]
- You can run to flat land
- Frame-based updating, which means if you have a 30fps panel it will run 2 times slower and an 120fps panel it will run 2 times faster + will run slow if your PC can't handle it,
- No way of selecting a block (?)
- If you're fast enough, you can run into an unloaded chunk, which makes you clip into the ground until you jump when the chunk is loaded.

**Comment by waldenn** [comment]
Good critical notes. [Upstream](https://github.com/rdfriedl/block-script) PR's / issues would be appreciated I think.

I just wanted to include a project like this as an example. Note though that this project is quite large in code size. Perhaps its better to focus on snake for now and return to this project later, but feel free to do what you want.

**Comment by joppiesaus** [comment]
Thanks for the info :+1:
