### ISSUE TITLE
Pages to learn/practice regex?

### ISSUE THREAD

**Issue by joppiesaus** [waldenn/spirare#16]
Pages to do with regular expressions featuring:
- learning
- practicing
- using in practice

I've personally found http://regexone.com/ very helpful.

**Comment by joppiesaus** [comment]
Let me go even further:
ES6 pages?

**Comment by waldenn** [comment]
Thanks, I will have a lookaround and add some regexp links.

ES6:
- https://github.com/lukehoban/es6features
- http://kangax.github.io/compat-table/es6/
