### ISSUE TITLE
Follow Three.js code style guideline

### ISSUE THREAD

**Issue by joppiesaus** [waldenn/spirare#4]
There aren't any uniform conventions for this project, I think it's a good idea to arrange them.

With uniform conventions I mean that all the code must look roughly the same.

Like both persons make this(just an example):

```
function doStuff(arg)
{
   arg = arg.Substring(0, 2);
}
```

And not person a:

```
function DoStuff(arg) {
   arg = arg.Substring ( 0, 2 );
}
```

when person b:

```
function dostuff(arg)
{
   arg = arg.Substring(
       0, 2
   );
}
```

**Comment by waldenn** [comment]
Ok, good idea.

The [Three.js project has a code-style guide](https://github.com/mrdoob/three.js/wiki/Mr.doob's-Code-Style%E2%84%A2). We could try to follow that.

**Comment by joppiesaus** [comment]
That's a good idea. I support that!

**Comment by waldenn** [comment]
It will take some time, but I will update the examples to conform to the Three.js style guide. Not a priority for now and...PR's accepted ofcourse : P
